// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbJZQwV3zZbtWvfGS48ttZaCknUY-iF8',
    appId: '1:345524851099:web:f8f8afc1c47047187f913e',
    messagingSenderId: '345524851099',
    projectId: 'carmania-4d8d7',
    authDomain: 'carmania-4d8d7.firebaseapp.com',
    storageBucket: 'carmania-4d8d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltDLhRHzmsvFjkg5_ubidGJpq8_hHitE',
    appId: '1:345524851099:android:17bc41f4a5427b037f913e',
    messagingSenderId: '345524851099',
    projectId: 'carmania-4d8d7',
    storageBucket: 'carmania-4d8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTg3W_SosYCvyGNOKHGbiCV35WApkGMI',
    appId: '1:345524851099:ios:843176e9a4ef79467f913e',
    messagingSenderId: '345524851099',
    projectId: 'carmania-4d8d7',
    storageBucket: 'carmania-4d8d7.appspot.com',
    iosClientId: '345524851099-lltkid1d38mtb4gjikegv8se2r0p2l7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.carmania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTg3W_SosYCvyGNOKHGbiCV35WApkGMI',
    appId: '1:345524851099:ios:843176e9a4ef79467f913e',
    messagingSenderId: '345524851099',
    projectId: 'carmania-4d8d7',
    storageBucket: 'carmania-4d8d7.appspot.com',
    iosClientId: '345524851099-lltkid1d38mtb4gjikegv8se2r0p2l7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.carmania',
  );
}
